parameters:
    clarity_wm.webmoney.manager.class: Clarity\WebMoneyBundle\Manager\WebMoney
    clarity_wm.webmoney.manager.wmid: %clarity_wm.wmid%
    clarity_wm.webmoney.manager.wmr: %clarity_wm.wmr%
    clarity_wm.webmoney.manager.signer_path: '%kernel.root_dir%/wmsigner/'
    clarity_wm.webmoney.client.class: Clarity\WebMoneyBundle\Client\WebMoneyClient
    clarity_wm.webmoney.client.url: https://w3s.webmoney.ru/asp/
    clarity_wm.webmoney.client.config:
        request.options:
            verify: false
            ssl_key: "%clarity_wm.webmoney.manager.signer_path%WebMoneyCA.pem.crt"
    # Abstract
    clarity_wm.abstract.manager.class: Clarity\WebMoneyBundle\Manager\AbstractManager


services:
## Managers configuration ##
    clarity_wm.webmoney.manager:
        class: "%clarity_wm.webmoney.manager.class%"
        arguments:
            - "@clarity_wm.webmoney.client"
            - "%clarity_wm.webmoney.manager.wmid%"
            - "%clarity_wm.webmoney.manager.wmr%"
            - "%clarity_wm.webmoney.manager.signer_path%"
        lazy: true
        public: true

## Clients configurations ##
    clarity_wm.webmoney.client:
        class: "%clarity_wm.webmoney.client.class%"
        arguments: ["%clarity_wm.webmoney.client.url%", "%clarity_wm.webmoney.client.config%"]
        calls:
            - ["setDescription", ["@clarity_wm.webmoney.client.service_description"]]
        tags:
            - {name: guzzle.client}

## Client description services ##
    clarity_wm.webmoney.client.service_description:
        class: "%guzzle.service_description.class%"
        factory_class: "%guzzle.service_description.class%"
        factory_method: factory
        arguments: ["%clarity_wm.webmoney.client.service_description.file_path%"]